name: 4H Scanner (Live Auto Push)

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scanner
        run: python htf_scanner_all20.py

      - name: Commit and push results
        run: |
          git config user.name "Subsonic Scanner Bot"
          git config user.email "actions@github.com"
          git add scan_results.csv
          git commit -m "Auto update: $(date)" || echo "No changes to commit"
          git push origin main
